# Generated by Django 2.1.5 on 2019-01-20 02:21

from django.db import migrations, models
import django.db.models.deletion
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_page_parent',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.CreateModel(
            name='test_page_child',
            fields=[
                ('test_page_parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.test_page_parent')),
                ('body', wagtailmd.utils.MarkdownField()),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.test_page_parent',),
        ),
        migrations.AddField(
            model_name='test_page_parent',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
