# Generated by Django 2.1.5 on 2019-01-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190120_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='project_overview',
            field=models.BooleanField(default=False),
        ),
    ]
