# Generated by Django 2.1.4 on 2018-12-29 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181229_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='blogpagetag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
