# Generated by Django 2.1.5 on 2019-01-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postpage_project_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='project_overview',
        ),
    ]
