# Generated by Django 2.1.4 on 2018-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181229_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='project_overview',
            field=models.BooleanField(default=False),
        ),
    ]
