# Generated by Django 2.1.5 on 2019-01-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0004_remove_postpage_project_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_page_child',
            name='test_page_parent_ptr',
        ),
        migrations.RemoveField(
            model_name='test_page_parent',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='test_page_parent',
            name='translatablepage_ptr',
        ),
        migrations.DeleteModel(
            name='test_page_child',
        ),
        migrations.DeleteModel(
            name='test_page_parent',
        ),
    ]
