# Generated by Django 2.1.4 on 2019-01-04 07:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('blog', '0004_blogcategory_shown_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostPageRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('shown_order', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Series',
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='related_page0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='related_page1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postpage',
            name='series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpagerelatedlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='blog.PostPage'),
        ),
        migrations.AddField(
            model_name='postpagerelatedlinks',
            name='related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='landingpagerelatedlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='blog.LandingPage'),
        ),
        migrations.AddField(
            model_name='landingpagerelatedlinks',
            name='related_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='series_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Series'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='series_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.Series'),
        ),
    ]
