# Generated by Django 2.1.4 on 2019-01-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190104_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='related_page0',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='related_page1',
        ),
    ]
