# Generated by Django 2.1.4 on 2019-01-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_landingpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
