# Generated by Django 2.1.4 on 2019-01-06 11:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190104_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
