# Generated by Django 2.1.4 on 2019-01-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_landingpage_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='color',
            new_name='banner_color',
        ),
    ]
