# Generated by Django 2.1.4 on 2019-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcategory_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindex',
            name='title_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
