# Generated by Django 2.1.4 on 2019-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190106_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='tilable_banner',
            field=models.BooleanField(default=False),
        ),
    ]
