# Generated by Django 2.1.5 on 2019-01-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('blog', '0010_auto_20190121_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='notebook_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
