# Generated by Django 2.1.4 on 2019-01-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_landingpage_tilable_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagerelatedlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedlinks',
            name='related_page',
        ),
        migrations.RemoveField(
            model_name='postpagerelatedlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='postpagerelatedlinks',
            name='related_page',
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedLinks',
        ),
        migrations.DeleteModel(
            name='PostPageRelatedLinks',
        ),
    ]
