# Generated by Django 2.1.4 on 2019-01-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('blog', '0012_landingpagerelatedlinks_postpagerelatedlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='landingpagerelatedlinks',
            name='related_page',
        ),
        migrations.RemoveField(
            model_name='postpagerelatedlinks',
            name='page',
        ),
        migrations.RemoveField(
            model_name='postpagerelatedlinks',
            name='related_page',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='related_page1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='related_page2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='related_page1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='related_page2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailtrans.TranslatablePage'),
        ),
        migrations.DeleteModel(
            name='LandingPageRelatedLinks',
        ),
        migrations.DeleteModel(
            name='PostPageRelatedLinks',
        ),
    ]
