# Generated by Django 2.1.4 on 2019-01-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('blog', '0013_auto_20190109_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='translatablepage_ptr',
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
    ]
