# Generated by Django 2.1.4 on 2018-12-23 14:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_caption', models.CharField(max_length=250)),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('data_title', models.CharField(max_length=50)),
                ('data_content', wagtail.core.fields.RichTextField(blank=True)),
                ('web_title', models.CharField(max_length=50)),
                ('web_content', wagtail.core.fields.RichTextField(blank=True)),
                ('game_title', models.CharField(max_length=50)),
                ('game_content', wagtail.core.fields.RichTextField(blank=True)),
                ('data_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('game_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('web_icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
