# Generated by Django 2.1.4 on 2019-01-03 08:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('title_caption', models.CharField(blank=True, max_length=250)),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('about_caption', models.CharField(blank=True, max_length=250)),
                ('about_content', wagtail.core.fields.RichTextField(blank=True)),
                ('data_title', models.CharField(blank=True, max_length=50)),
                ('data_content', wagtail.core.fields.RichTextField(blank=True)),
                ('web_title', models.CharField(blank=True, max_length=50)),
                ('web_content', wagtail.core.fields.RichTextField(blank=True)),
                ('game_title', models.CharField(blank=True, max_length=50)),
                ('game_content', wagtail.core.fields.RichTextField(blank=True)),
                ('tutorial_title', models.CharField(blank=True, max_length=50)),
                ('tutorial_content', wagtail.core.fields.RichTextField(blank=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
    ]
