# Generated by Django 2.1.5 on 2019-01-15 14:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailmd.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailtrans', '0007_auto_20180327_1127'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('head', models.CharField(blank=True, max_length=30)),
                ('head_intro', models.CharField(blank=True, max_length=80)),
                ('name_intro0', models.CharField(blank=True, max_length=80)),
                ('name_intro1', models.CharField(blank=True, max_length=80)),
                ('assist', models.CharField(blank=True, max_length=80)),
                ('due', models.CharField(blank=True, max_length=80)),
                ('plan_intro', models.CharField(blank=True, max_length=80)),
                ('mail_intro', models.CharField(blank=True, max_length=80)),
                ('thanks', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.CreateModel(
            name='ContactMeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('receive_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HireMe',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('title_caption', models.CharField(blank=True, max_length=80)),
                ('Flow', wagtailmd.utils.MarkdownField(blank=True)),
                ('Task', wagtailmd.utils.MarkdownField(blank=True)),
                ('Plan', wagtailmd.utils.MarkdownField(blank=True)),
                ('Charge', wagtailmd.utils.MarkdownField(blank=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('translatablepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailtrans.TranslatablePage')),
                ('title_caption', models.CharField(blank=True, max_length=250)),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('about_caption', models.CharField(blank=True, max_length=250)),
                ('about_content', wagtail.core.fields.RichTextField(blank=True)),
                ('data_title', models.CharField(blank=True, max_length=50)),
                ('data_content', wagtail.core.fields.RichTextField(blank=True)),
                ('web_title', models.CharField(blank=True, max_length=50)),
                ('web_content', wagtail.core.fields.RichTextField(blank=True)),
                ('game_title', models.CharField(blank=True, max_length=50)),
                ('game_content', wagtail.core.fields.RichTextField(blank=True)),
                ('tutorial_title', models.CharField(blank=True, max_length=50)),
                ('tutorial_content', wagtail.core.fields.RichTextField(blank=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailtrans.translatablepage',),
        ),
        migrations.CreateModel(
            name='plan_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_en', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_en', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='contactmedata',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.plan_type'),
        ),
        migrations.AddField(
            model_name='contactmedata',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.task_type'),
        ),
    ]
