# Generated by Django 2.1.5 on 2019-01-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsciber_email', models.EmailField(max_length=50)),
                ('receive_time', models.DateTimeField()),
            ],
        ),
    ]
