# Generated by Django 2.1.4 on 2018-12-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181229_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='about_context',
            new_name='about_content',
        ),
    ]
