# Generated by Django 2.1.4 on 2019-01-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190108_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_type',
            name='name_en',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='task_type',
            name='name_en',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
