# Generated by Django 2.1.4 on 2018-12-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181229_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='data_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='game_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='web_icon',
        ),
    ]
