# Generated by Django 2.1.4 on 2019-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190108_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmedata',
            name='due_date',
            field=models.CharField(max_length=100),
        ),
    ]
