# Generated by Django 2.1.4 on 2019-01-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190108_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmedata',
            name='receive_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
