# Generated by Django 2.1.4 on 2019-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmedata_receive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmedata',
            name='receive_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
