# Generated by Django 2.1.4 on 2019-01-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190108_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='assist',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='due',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='head_intro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='mail_intro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='name_intro0',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='name_intro1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='plan_intro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='thanks',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
