# Generated by Django 2.1.4 on 2019-01-09 14:01

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190109_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireme',
            name='Charge',
            field=wagtailmd.utils.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='hireme',
            name='Flow',
            field=wagtailmd.utils.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='hireme',
            name='Plan',
            field=wagtailmd.utils.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='hireme',
            name='Task',
            field=wagtailmd.utils.MarkdownField(blank=True),
        ),
    ]
