# Generated by Django 2.1.5 on 2019-01-31 13:47

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppost',
            name='app_description',
        ),
        migrations.RemoveField(
            model_name='apppost',
            name='component_name',
        ),
        migrations.AddField(
            model_name='apppost',
            name='body_after_app',
            field=wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('custom_html', wagtail.core.blocks.TextBlock(icon='plus-inverse'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apppost',
            name='body_before_app',
            field=wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('custom_html', wagtail.core.blocks.TextBlock(icon='plus-inverse'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apppost',
            name='dash_ratio',
            field=models.FloatField(default=0.5, help_text='The ratio of height to width.  Will inherit its width as 100\\% of its parent, then set height'),
        ),
    ]
