# Generated by Django 2.1.5 on 2019-01-31 14:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190131_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='body_after_app',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('custom_html', wagtail.core.blocks.TextBlock(icon='plus-inverse'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='body_before_app',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('custom_html', wagtail.core.blocks.TextBlock(icon='plus-inverse'))], blank=True, null=True),
        ),
    ]
