# Generated by Django 2.1.5 on 2019-01-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('apps', '0003_auto_20190111_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='appindex',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
