# Generated by Django 2.1.5 on 2019-01-13 05:33

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20190111_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='app_description',
            field=wagtailmd.utils.MarkdownField(blank=True),
        ),
    ]
